Chat/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.ChatView.as_view(), name='chat_page'),
    path('<int:pk>/', login_required(views.MessageEditView.as_view()), name='edit_msg_page'),
]

Main/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken.views import obtain_auth_token

from DRF_app.urls import router

urlpatterns = [
    path('api/token/', obtain_auth_token, name='api-token'),
    path('api/', include(router.urls)),
    path('', include('social_django.urls', namespace='social')),
    path('', include('IndexApp.urls')),
    path('admin/', admin.site.urls, name='django_admin'),
    path('chat/', include('Chat.urls')),
    path('todo/', include('ToDoApp.urls')),
]

Chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session


class Message(models.Model):

    text = models.TextField(null=False, blank=False)
    sent = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    edited = models.DateTimeField(auto_now=True, null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    anonymous_author = models.ForeignKey(Session, on_delete=models.CASCADE, null=True)
    image = models.ImageField(upload_to='Chat/messages/imgs', null=True, blank=True)

    def __str__(self):
        return ('%s, %s: %s..' % (self.sent, self.author, self.text[:15]))

templates/blocks/footer.html
<footer>

</footer>

templates/blocks/header.html
<header>
	<a href="{% url 'index_page' %}" id="header_main">Главная</a>
	<a href="/api/">DRF API</a>
	<a href="/admin/">Admin Panel</a>
	<a href="{% url 'todo_page' %}">To-Do</a>
	<a href="{% url 'about_us' %}">About us</a>
	<a href="{% url 'chat_page' %}#id_text">Chat</a>
	{% if user.is_authenticated %}
	<a href="{% url 'profile_page' request.user.profile.pk %}">{{ user.username }}</a>
	<a id="logout" href="{% url 'logout' %}">Выйти</a>
	{% else %}
	<a href="{% url 'login' %}">Войти</a>
	<a href="{% url 'signup' %}">Регистрация</a>
	{% endif %}
</header>

templates/blocks/links.html
{% load static %}
<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/common.css' %}">

<!-- FONTS -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Play&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@200&display=swap" rel="stylesheet">